services:
  - type: web
    name: aksamedika-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./apps/api
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 8080
